/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Adminstratos
 */
public class StudentManagement extends javax.swing.JFrame {

    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label_studentManagement = new javax.swing.JLabel();
        label_Id = new javax.swing.JLabel();
        textField_Id = new javax.swing.JTextField();
        label_Email = new javax.swing.JLabel();
        textField_StudentName = new javax.swing.JTextField();
        label_StudentName = new javax.swing.JLabel();
        textField_Email = new javax.swing.JTextField();
        label_Birthday = new javax.swing.JLabel();
        textField_Birthday = new javax.swing.JTextField();
        label_Sex = new javax.swing.JLabel();
        RDB_Male = new javax.swing.JRadioButton();
        RDB_Female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Student = new javax.swing.JTable();
        button_Add = new javax.swing.JButton();
        button_Update = new javax.swing.JButton();
        button_Delete = new javax.swing.JButton();
        label_PhoneNumber = new javax.swing.JLabel();
        textField_PhoneNumber = new javax.swing.JTextField();
        button_Search = new javax.swing.JButton();
        button__Close = new javax.swing.JButton();
        label_Search = new javax.swing.JLabel();
        textField_Search = new javax.swing.JTextField();
        button_Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_studentManagement.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_studentManagement.setForeground(new java.awt.Color(102, 102, 0));
        label_studentManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_studentManagement.setText("STUDENT MANAGEMENT");
        label_studentManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        label_Id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_Id.setText("ID:");

        textField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_IdActionPerformed(evt);
            }
        });

        label_Email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_Email.setText("Email:");

        textField_StudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_StudentNameActionPerformed(evt);
            }
        });

        label_StudentName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_StudentName.setText("Student name:");

        textField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_EmailActionPerformed(evt);
            }
        });
        textField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField_EmailKeyReleased(evt);
            }
        });

        label_Birthday.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_Birthday.setText("Birthday:");

        textField_Birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_BirthdayActionPerformed(evt);
            }
        });

        label_Sex.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_Sex.setText("Sex:");

        buttonGroup1.add(RDB_Male);
        RDB_Male.setSelected(true);
        RDB_Male.setText("Male");
        RDB_Male.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RDB_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDB_MaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(RDB_Female);
        RDB_Female.setText("Female");
        RDB_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDB_FemaleActionPerformed(evt);
            }
        });

        tb_Student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student name", "Sex", "Email", "Phone number", "Birthday"
            }
        ));
        tb_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_StudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Student);

        button_Add.setBackground(new java.awt.Color(204, 204, 204));
        button_Add.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 14)); // NOI18N
        button_Add.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adminstratos\\Downloads\\icons8-add-20.png")); // NOI18N
        button_Add.setText("Add");
        button_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddActionPerformed(evt);
            }
        });

        button_Update.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 14)); // NOI18N
        button_Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adminstratos\\Downloads\\icons8-edit-20.png")); // NOI18N
        button_Update.setText("Update");
        button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UpdateActionPerformed(evt);
            }
        });

        button_Delete.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 14)); // NOI18N
        button_Delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adminstratos\\Downloads\\icons8-delete-20.png")); // NOI18N
        button_Delete.setText("Delete");
        button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DeleteActionPerformed(evt);
            }
        });

        label_PhoneNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_PhoneNumber.setText("Phone number:");

        button_Search.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 14)); // NOI18N
        button_Search.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adminstratos\\Downloads\\icons8-search-20.png")); // NOI18N
        button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SearchActionPerformed(evt);
            }
        });

        button__Close.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 14)); // NOI18N
        button__Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adminstratos\\Downloads\\icons8-close-window-20.png")); // NOI18N
        button__Close.setText("Close");
        button__Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button__CloseActionPerformed(evt);
            }
        });

        label_Search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_Search.setText("Search ID:");

        button_Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button_Save.setText("Save");
        button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Id)
                            .addComponent(label_StudentName)
                            .addComponent(label_Email)
                            .addComponent(label_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_studentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(177, 177, 177))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(label_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(textField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_Add)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_Update)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button__Close, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textField_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(textField_Birthday, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(textField_PhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RDB_Male)
                                                .addGap(18, 18, 18)
                                                .addComponent(RDB_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(button_Save))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(24, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_PhoneNumber)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_Sex)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(label_studentManagement)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_Search)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_Search)
                            .addComponent(textField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_Id))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_Sex)
                                    .addComponent(RDB_Male)
                                    .addComponent(RDB_Female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(134, 134, 134))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_StudentName)
                                    .addComponent(textField_StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textField_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_Birthday)
                                    .addComponent(textField_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Save))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_Update)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Delete)
                            .addComponent(button__Close))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_IdActionPerformed

    private void RDB_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDB_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDB_MaleActionPerformed

    private void textField_BirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_BirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_BirthdayActionPerformed

    private void button_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddActionPerformed
        // TODO add your handling code here:
        String gender;
        if (RDB_Male.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }
        if (textField_Id.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the ID");
        } else if (textField_StudentName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Name");
        } else if (textField_Email.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Email");
        } else if (textField_PhoneNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the PhoneNumber");
        } else if (textField_Birthday.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Birthday");
        } else {
            DefaultTableModel tb_model = (DefaultTableModel) tb_Student.getModel();
            String table[] = {textField_Id.getText(), textField_StudentName.getText(), gender, textField_Email.getText(), textField_PhoneNumber.getText(), textField_Birthday.getText()};
            tb_model.addRow(table);
            JOptionPane.showMessageDialog(this, "OK");

        }
    }//GEN-LAST:event_button_AddActionPerformed

    private void button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb_Model = (DefaultTableModel) tb_Student.getModel();
        if (tb_Student.getSelectedRowCount() == 1) {
            String id = textField_Id.getText();
            String studentName = textField_StudentName.getText();
            String gender = buttonGroup1.getSelection().getActionCommand();
            RDB_Male.setActionCommand("Male");
            RDB_Female.setActionCommand("Female");
            String email = textField_Email.getText();
            Object phoneNumber = textField_PhoneNumber.getText();
            String birthday = textField_Birthday.getText();
            tb_Model.setValueAt(id, tb_Student.getSelectedRow(), 0);
            tb_Model.setValueAt(studentName, tb_Student.getSelectedRow(), 1);
            tb_Model.setValueAt(gender, tb_Student.getSelectedRow(), 2);
            tb_Model.setValueAt(email, tb_Student.getSelectedRow(), 3);
            tb_Model.setValueAt(phoneNumber, tb_Student.getSelectedRow(), 4);
            tb_Model.setValueAt(birthday, tb_Student.getSelectedRow(), 5);
            JOptionPane.showMessageDialog(this, "Edit ok");
    }//GEN-LAST:event_button_UpdateActionPerformed
else {
            if (tb_Student.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please seclect");
            }
        }
    }
    private void tb_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_StudentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb_Model = (DefaultTableModel) tb_Student.getModel();
        String tb_Id = tb_Model.getValueAt(tb_Student.getSelectedRow(), 0).toString();
        String tb_StudentName = tb_Model.getValueAt(tb_Student.getSelectedRow(), 1).toString();
        Object tb_Gender = tb_Model.getValueAt(tb_Student.getSelectedRow(), 2).toString();
        String tb_Email = tb_Model.getValueAt(tb_Student.getSelectedRow(), 3).toString();
        String tb_PhoneNumber = tb_Model.getValueAt(tb_Student.getSelectedRow(), 4).toString();
        String tb_Birthday = tb_Model.getValueAt(tb_Student.getSelectedRow(), 5).toString();
        textField_Id.setText(tb_Id);
        textField_StudentName.setText(tb_StudentName);

        if (tb_Gender == "Male") {
            RDB_Male.doClick();
            String Gender = "Male";
        } else {
            RDB_Female.doClick();
            String Gender = "Female";
        }
        textField_Email.setText(tb_Email);
        textField_PhoneNumber.setText(tb_PhoneNumber);
        textField_Birthday.setText(tb_Birthday);

    }//GEN-LAST:event_tb_StudentMouseClicked

    private void textField_StudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_StudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_StudentNameActionPerformed

    private void textField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_EmailActionPerformed

    private void RDB_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDB_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDB_FemaleActionPerformed

    private void button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb_model = (DefaultTableModel) tb_Student.getModel();
        if (tb_Student.getSelectedRowCount() == 1) {
            tb_model.removeRow(tb_Student.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Remove ok");
        } else {
            if (tb_Student.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please select");
            }
        }
    }//GEN-LAST:event_button_DeleteActionPerformed
    private JFrame jframe;
    private void button__CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button__CloseActionPerformed
        // TODO add your handling code here:
        jframe = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(jframe, "Do you want to exit this program?", "Exit",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_button__CloseActionPerformed

    public void search(String idRequest) {
        DefaultTableModel tb_Model = (DefaultTableModel) tb_Student.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(tb_Model);
        tb_Student.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(idRequest));
    }
    private void button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SearchActionPerformed
        // TODO add your handling code here:
        String idRequest = JOptionPane.showInputDialog("ID", "Type here");
        search(idRequest);
    }//GEN-LAST:event_button_SearchActionPerformed

    private void textField_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField_EmailKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_textField_EmailKeyReleased

    private void button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RDB_Female;
    private javax.swing.JRadioButton RDB_Male;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_Add;
    private javax.swing.JButton button_Delete;
    private javax.swing.JButton button_Save;
    private javax.swing.JButton button_Search;
    private javax.swing.JButton button_Update;
    private javax.swing.JButton button__Close;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Birthday;
    private javax.swing.JLabel label_Email;
    private javax.swing.JLabel label_Id;
    private javax.swing.JLabel label_PhoneNumber;
    private javax.swing.JLabel label_Search;
    private javax.swing.JLabel label_Sex;
    private javax.swing.JLabel label_StudentName;
    private javax.swing.JLabel label_studentManagement;
    public javax.swing.JTable tb_Student;
    private javax.swing.JTextField textField_Birthday;
    private javax.swing.JTextField textField_Email;
    private javax.swing.JTextField textField_Id;
    private javax.swing.JTextField textField_PhoneNumber;
    private javax.swing.JTextField textField_Search;
    private javax.swing.JTextField textField_StudentName;
    // End of variables declaration//GEN-END:variables
}
