/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagement;

import model.Student;
import model.StudentList;

import javax.swing.*;
import java.awt.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author Adminstratos
 */
public class Student_Management extends javax.swing.JFrame {

    /**
     * Creates new form Student_Management
     */
    public Student_Management() {
        initComponents();
    }
    SimpleDateFormat dateFormat=new SimpleDateFormat("dd/MM/yyyy");
    StudentList myStudentList=new StudentList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        label_studentManagement = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        textfield_id = new javax.swing.JTextField();
        label_studentName = new javax.swing.JLabel();
        textField_studentName = new javax.swing.JTextField();
        label_phoneNumber = new javax.swing.JLabel();
        textField_phoneNumber = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        textField_email = new javax.swing.JTextField();
        label_birthday = new javax.swing.JLabel();
        textField_birthday = new javax.swing.JTextField();
        label_sex = new javax.swing.JLabel();
        radioButton_male = new javax.swing.JRadioButton();
        radioButton_female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button_add = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_studentManagement.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        label_studentManagement.setForeground(new java.awt.Color(102, 102, 0));
        label_studentManagement.setText("STUDENT MANAGEMENT");

        label_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_id.setText("ID:");

        textfield_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_idActionPerformed(evt);
            }
        });

        label_studentName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_studentName.setText("Student name:");

        textField_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_studentNameActionPerformed(evt);
            }
        });

        label_phoneNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_phoneNumber.setText("Phone Number:");

        textField_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_phoneNumberActionPerformed(evt);
            }
        });

        label_email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_email.setText("Email:");

        textField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_emailActionPerformed(evt);
            }
        });

        label_birthday.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_birthday.setText("Birthday:");

        textField_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_birthdayActionPerformed(evt);
            }
        });

        label_sex.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label_sex.setText("Sex:");

        buttonGroup1.add(radioButton_male);
        radioButton_male.setText("Male");

        buttonGroup1.add(radioButton_female);
        radioButton_female.setText("Female");
        radioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_femaleActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student name", "Sex", "Phone Number", "Email", "Birthday"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        button_add.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 14)); // NOI18N
        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_save.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 1, 14)); // NOI18N
        button_save.setText("Save");

        button_update.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 14)); // NOI18N
        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_delete.setFont(new java.awt.Font("UD Digi Kyokasho NP-B", 0, 14)); // NOI18N
        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_sex)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_studentName)
                                            .addComponent(label_id)
                                            .addComponent(label_phoneNumber)
                                            .addComponent(label_email)
                                            .addComponent(label_birthday))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textField_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textField_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(radioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(radioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(textfield_id)
                                                .addComponent(textField_studentName))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(label_studentManagement)))
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_studentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(textfield_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_studentName))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sex)
                    .addComponent(radioButton_male)
                    .addComponent(radioButton_female))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_email)))
                    .addComponent(label_phoneNumber))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_birthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_add)
                    .addComponent(button_update)
                    .addComponent(button_delete)
                    .addComponent(button_save))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_idActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            Student student=getModel();
            if(myStudentList.add(student)>0){
                JOptionPane.showMessageDialog(this,"Save success");
                fillDataTable();
                reset();
            }
        }
    }//GEN-LAST:event_textfield_idActionPerformed
    public boolean validateForm(){
        if(textfield_id.getText().isEmpty()
                ||textField_studentName.getText().isEmpty()
                ||textField_email.getText().isEmpty()
                ||textField_phoneNumber.getText().isEmpty()
                ||textField_birthday.getText().isEmpty()){
            return false;
        }
        return true;
    }
    public Student getModel(){
        Student student= new Student();
        student.setName(textField_studentName.getText());
        student.setId(textfield_id.getText());
        try{
            student.setBirthday(dateFormat.parse(textField_birthday.getText()));
        }catch (ParseException e){
            System.out.println("Error: "+e.toString());
        }
        student.setEmail(textField_email.getText());
        boolean sex=false;
        if (radioButton_male.isSelected()){
            sex=true;
        }
        student.setSex(sex);
        student.setPhoneNumber(textField_phoneNumber.getText());
        return student;


    }

    private void textField_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_studentNameActionPerformed

    private void textField_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_phoneNumberActionPerformed

    private void textField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_emailActionPerformed

    private void textField_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_birthdayActionPerformed

    private void radioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_femaleActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_addActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_updateActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_birthday;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_phoneNumber;
    private javax.swing.JLabel label_sex;
    private javax.swing.JLabel label_studentManagement;
    private javax.swing.JLabel label_studentName;
    private javax.swing.JRadioButton radioButton_female;
    private javax.swing.JRadioButton radioButton_male;
    private javax.swing.JTextField textField_birthday;
    private javax.swing.JTextField textField_email;
    private javax.swing.JTextField textField_phoneNumber;
    private javax.swing.JTextField textField_studentName;
    private javax.swing.JTextField textfield_id;
    // End of variables declaration//GEN-END:variables
}
